name: Terraform Apply

on:
  push:
    branches: [main]
    paths: 
      - 'terraform/raisetech/modules/**/*.tf'
      - 'terraform/raisetech/environments/**/*.tf'
      - 'terraform/raisetech/environments/**/*.tfvars'
      - 'terraform/raisetech/environments/**/*.tftest.hcl'
      - '.github/workflows/*.yaml'

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    environment:
      name: dev

    env:
      TF_VAR_my_ip: ${{ secrets.MY_IP }}
      TF_VAR_ec2_keypair: ${{ secrets.EC2_KEYPAIR }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_alarm_email: ${{ secrets.ALARM_EMAIL }}
      AWS_DEFAULT_REGION: ap-northeast-1

    defaults:
      run:
        working-directory: terraform/raisetech/environments/dev

    permissions:
      id-token: write
      contents: read  

    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.4

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      
      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve